# Copyright 2025 dah4k
# SPDX-License-Identifier: EPL-2.0

FROM opensuse/leap:16.0

## Restore man-pages and other documentation
RUN sed -i 's/^rpm.install.excludedocs.*/rpm.install.excludedocs = no/' /etc/zypp/zypp.conf

## Install packages
RUN zypper --quiet --non-interactive refresh \
 && zypper --quiet --non-interactive install --no-recommends \
        binutils \
        cross-arm-binutils \
        cross-arm-gcc15 \
        cross-arm-linux-glibc-devel \
        curl \
        dnsmasq \
        fd \
        file \
        gcc \
        gcc-c++ \
        gdb \
        git \
        iproute2 \
        iptables \
        jq \
        make \
        man \
        man-pages \
        man-pages-posix \
        netcat-openbsd \
        openssh \
        qemu-arm \
        qemu-headless \
        qemu-img \
        qemu-microvm \
        qemu-tools \
        ripgrep \
        socat \
        tar \
        tinyproxy \
        velociraptor \
        vim \
        vim-data \
        xz \
 && zypper --quiet --non-interactive clean

## Create user
ARG USERNAME=osdev
RUN groupadd --gid 1000 ${USERNAME} \
 && useradd --create-home --home-dir /home/${USERNAME} --uid 1000 --gid 1000 ${USERNAME}

COPY --chown=osdev:osdev files/bashrc /home/${USERNAME}/.bashrc
COPY --chown=osdev:osdev files/alias /home/${USERNAME}/.alias

USER ${USERNAME}

WORKDIR /home/${USERNAME}

