# Copyright 2025 dah4k
# SPDX-License-Identifier: EPL-2.0

FROM opensuse/leap:16.0

## Restore man-pages and other documentation
RUN sed -i 's/^rpm.install.excludedocs.*/rpm.install.excludedocs = no/' /etc/zypp/zypp.conf

## Install packages
RUN zypper --quiet --non-interactive refresh \
 && zypper --quiet --non-interactive install --no-recommends \
        ## Virtmg-NG dependencies \
        ## https://github.com/arighi/virtme-ng/blob/main/.github/workflows/run.yml#L21-L24 \
        busybox-static \
        coreutils \
        file \
        git \
        iproute2 \
        kbd \
        kmod \
        libvirt-client \
        libvirt-client-qemu \
        python313-argcomplete \
        python313-requests \
        qemu \
        rsync \
        udev \
        virtiofsd \
        zstd \
        ## Virtmg-NG requires dpkg missing on RPM-based system \
        dpkg \
        virtme \
        ## Velociraptor additional build requirements \
        ## README.md mentions Node v18.14.2 which was EOL since 2025... \
        ## Github Action CI uses Go 1.25 and Node v22.19 on Ubuntu 22.04 \
        go1.25 \
        nodejs22 \
        npm22 \
        velociraptor \
        ## Personal preferences \
        curl \
        fd \
        ripgrep \
        tmux \
        tokei \
        vim \
        vim-data \
 && zypper --quiet --non-interactive clean

## Workaround missing Ubuntu python-is-python3 package
RUN ln -s /usr/bin/python3 /usr/bin/python

## FIXME: Setup KVM support in container
## See Also https://forums.docker.com/t/udevadm-control-reload-rules/135564
RUN echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' > /etc/udev/rules.d/99-kvm4all.rules
#RUN /lib/systemd/systemd-udevd --daemon
#RUN udevadm control --reload-rules
#RUN udevadm trigger --name-match=kvm

## Create user
ARG USERNAME=osdev
RUN groupadd --gid 1000 ${USERNAME} \
 && useradd --create-home --home-dir /home/${USERNAME} --uid 1000 --gid 1000 ${USERNAME}

COPY --chown=1000:1000 files/bashrc /home/${USERNAME}/.bashrc
COPY --chown=1000:1000 files/alias /home/${USERNAME}/.alias

USER ${USERNAME}

WORKDIR /home/${USERNAME}

RUN git clone https://github.com/arighi/virtme-ng \
 && git clone https://github.com/Velocidex/velociraptor
