# Copyright 2025 dah4k
# SPDX-License-Identifier: EPL-2.0

FROM opensuse/leap:16.0

## Restore man-pages and other documentation
RUN sed -i 's/^rpm.install.excludedocs.*/rpm.install.excludedocs = no/' /etc/zypp/zypp.conf

## Install packages
RUN zypper --quiet --non-interactive refresh \
 && zypper --quiet --non-interactive install --no-recommends \
        binutils \
        cross-arm-binutils \
        cross-arm-gcc15 \
        cross-arm-linux-glibc-devel \
        curl \
        dnsmasq \
        fd \
        file \
        gcc \
        gcc-c++ \
        gdb \
        git \
        iproute2 \
        iptables \
        jq \
        make \
        man \
        man-pages \
        man-pages-posix \
        netcat-openbsd \
        openssh \
        qemu-arm \
        qemu-extra \
        qemu-headless \
        qemu-img \
        qemu-microvm \
        qemu-tools \
        qemu-x86 \
        ripgrep \
        socat \
        tar \
        tinyproxy \
        velociraptor \
        vim \
        vim-data \
        xz \
        ## Velociraptor additional build requirements \
        ## README.md mentions Node v18.14.2 which was EOL since 2025... \
        ## Github Action CI uses Go 1.25 and Node v22.19 on Ubuntu 22.04 \
        go1.25 \
        nodejs22 \
        npm22 \
        ## JetKVM RV1106 additional build requirements \
        autoconf \
        automake \
        bc \
        bison \
        bzip2 \
        cmake \
        dbus-1-devel \
        dpkg-devel \
        dtc \
        dwarves \
        ed \
        fakeroot \
        flex \
        gperf \
        iproute2 \
        kmod \
        libelf-devel \
        libgcrypt-devel \
        libnl3-devel \
        libopenssl-devel \
        m4 \
        mpc-devel \
        openssl \
        python313 \
        sequoia-sq \
        texinfo \
 && zypper --quiet --non-interactive clean

## Create user
ARG USERNAME=osdev
RUN groupadd --gid 1000 ${USERNAME} \
 && useradd --create-home --home-dir /home/${USERNAME} --uid 1000 --gid 1000 ${USERNAME}

COPY --chown=1000:1000 files/bashrc /home/${USERNAME}/.bashrc
COPY --chown=1000:1000 files/alias /home/${USERNAME}/.alias

USER ${USERNAME}

WORKDIR /home/${USERNAME}

RUN git clone https://github.com/Velocidex/velociraptor \
 && git clone https://github.com/jetkvm/kvm \
 && git clone https://github.com/jetkvm/rv1106-system
